name: ESLint Check

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout codes
        uses: actions/checkout@v2

      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2









 