name: ESLint Check

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout codes
        uses: actions/checkout@v2

      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies for server
        run: npm install
        working-directory: server
        
      - name: Run ESLint server
        working-directory: server
        uses: stefanoeb/eslint-action@1.0.2

      - name: Install dependencies for client
        run: npm install
        working-directory: client
        
      - name: Run ESLint for client
        working-directory: client
        uses: stefanoeb/eslint-action@1.0.2
